[package]
name = "podgen"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
rust-ini = "0.20" # no serde support

names = { version = "0.14", default-features = false }

clap = { version = "4", features = ["derive"] }
